(cl:defpackage obj_recognition-msg
  (:use )
  (:export
   "<COLLISIONOBJECTS>"
   "COLLISIONOBJECTS"
   "<DETECTEDOBJECT>"
   "DETECTEDOBJECT"
   "<DETECTEDOBJECTSARRAY>"
   "DETECTEDOBJECTSARRAY"
   "<JOINTCOMMAND>"
   "JOINTCOMMAND"
   "<SEGMENTEDCLUSTERSARRAY>"
   "SEGMENTEDCLUSTERSARRAY"
  ))

