; Auto-generated. Do not edit!


(cl:in-package vizzy_msgs-msg)


;//! \htmlinclude CartesianFeedback.msg.html

(cl:defclass <CartesianFeedback> (roslisp-msg-protocol:ros-message)
  ((current_e_eff_pose
    :reader current_e_eff_pose
    :initarg :current_e_eff_pose
    :type geometry_msgs-msg:PoseStamped
    :initform (cl:make-instance 'geometry_msgs-msg:PoseStamped)))
)

(cl:defclass CartesianFeedback (<CartesianFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CartesianFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CartesianFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name vizzy_msgs-msg:<CartesianFeedback> is deprecated: use vizzy_msgs-msg:CartesianFeedback instead.")))

(cl:ensure-generic-function 'current_e_eff_pose-val :lambda-list '(m))
(cl:defmethod current_e_eff_pose-val ((m <CartesianFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader vizzy_msgs-msg:current_e_eff_pose-val is deprecated.  Use vizzy_msgs-msg:current_e_eff_pose instead.")
  (current_e_eff_pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CartesianFeedback>) ostream)
  "Serializes a message object of type '<CartesianFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_e_eff_pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CartesianFeedback>) istream)
  "Deserializes a message object of type '<CartesianFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_e_eff_pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CartesianFeedback>)))
  "Returns string type for a message object of type '<CartesianFeedback>"
  "vizzy_msgs/CartesianFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CartesianFeedback)))
  "Returns string type for a message object of type 'CartesianFeedback"
  "vizzy_msgs/CartesianFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CartesianFeedback>)))
  "Returns md5sum for a message object of type '<CartesianFeedback>"
  "a559431a983ef774411750928f6599f4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CartesianFeedback)))
  "Returns md5sum for a message object of type 'CartesianFeedback"
  "a559431a983ef774411750928f6599f4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CartesianFeedback>)))
  "Returns full string definition for message of type '<CartesianFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/PoseStamped current_e_eff_pose~%~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CartesianFeedback)))
  "Returns full string definition for message of type 'CartesianFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/PoseStamped current_e_eff_pose~%~%~%~%================================================================================~%MSG: geometry_msgs/PoseStamped~%# A Pose with reference coordinate frame and timestamp~%Header header~%Pose pose~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CartesianFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_e_eff_pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CartesianFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CartesianFeedback
    (cl:cons ':current_e_eff_pose (current_e_eff_pose msg))
))
