// Auto-generated. Do not edit!

// (in-package vizzy_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class CartesianResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.state_reached = null;
      this.end_effector_pose = null;
    }
    else {
      if (initObj.hasOwnProperty('state_reached')) {
        this.state_reached = initObj.state_reached
      }
      else {
        this.state_reached = false;
      }
      if (initObj.hasOwnProperty('end_effector_pose')) {
        this.end_effector_pose = initObj.end_effector_pose
      }
      else {
        this.end_effector_pose = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CartesianResult
    // Serialize message field [state_reached]
    bufferOffset = _serializer.bool(obj.state_reached, buffer, bufferOffset);
    // Serialize message field [end_effector_pose]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.end_effector_pose, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CartesianResult
    let len;
    let data = new CartesianResult(null);
    // Deserialize message field [state_reached]
    data.state_reached = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [end_effector_pose]
    data.end_effector_pose = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.end_effector_pose);
    return length + 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'vizzy_msgs/CartesianResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '480f367d9a3455de8c5b570394393f40';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #result definition
    bool state_reached
    geometry_msgs/PoseStamped end_effector_pose
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CartesianResult(null);
    if (msg.state_reached !== undefined) {
      resolved.state_reached = msg.state_reached;
    }
    else {
      resolved.state_reached = false
    }

    if (msg.end_effector_pose !== undefined) {
      resolved.end_effector_pose = geometry_msgs.msg.PoseStamped.Resolve(msg.end_effector_pose)
    }
    else {
      resolved.end_effector_pose = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = CartesianResult;
