// Generated by gencpp from file id_selector/BBList.msg
// DO NOT EDIT!


#ifndef ID_SELECTOR_MESSAGE_BBLIST_H
#define ID_SELECTOR_MESSAGE_BBLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <id_selector/BoundingBox.h>

namespace id_selector
{
template <class ContainerAllocator>
struct BBList_
{
  typedef BBList_<ContainerAllocator> Type;

  BBList_()
    : header()
    , bbVector()  {
    }
  BBList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bbVector(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::id_selector::BoundingBox_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::id_selector::BoundingBox_<ContainerAllocator> >::other >  _bbVector_type;
  _bbVector_type bbVector;





  typedef boost::shared_ptr< ::id_selector::BBList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::id_selector::BBList_<ContainerAllocator> const> ConstPtr;

}; // struct BBList_

typedef ::id_selector::BBList_<std::allocator<void> > BBList;

typedef boost::shared_ptr< ::id_selector::BBList > BBListPtr;
typedef boost::shared_ptr< ::id_selector::BBList const> BBListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::id_selector::BBList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::id_selector::BBList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace id_selector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'id_selector': ['/home/miguel/catkin_ws/src/vizzy/vizzy_ros_android_bridges/id_selector/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::id_selector::BBList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::id_selector::BBList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::id_selector::BBList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::id_selector::BBList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::id_selector::BBList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::id_selector::BBList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::id_selector::BBList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "451051af5703a61c3d4949dd71734381";
  }

  static const char* value(const ::id_selector::BBList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x451051af5703a61cULL;
  static const uint64_t static_value2 = 0x3d4949dd71734381ULL;
};

template<class ContainerAllocator>
struct DataType< ::id_selector::BBList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "id_selector/BBList";
  }

  static const char* value(const ::id_selector::BBList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::id_selector::BBList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
BoundingBox[] bbVector\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: id_selector/BoundingBox\n\
int32 id\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
bool tracked\n\
geometry_msgs/Point person3dLocation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::id_selector::BBList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::id_selector::BBList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bbVector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::id_selector::BBList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::id_selector::BBList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bbVector[]" << std::endl;
    for (size_t i = 0; i < v.bbVector.size(); ++i)
    {
      s << indent << "  bbVector[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::id_selector::BoundingBox_<ContainerAllocator> >::stream(s, indent + "    ", v.bbVector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ID_SELECTOR_MESSAGE_BBLIST_H
