// Generated by gencpp from file vizzy_msgs/CartesianGoal.msg
// DO NOT EDIT!


#ifndef VIZZY_MSGS_MESSAGE_CARTESIANGOAL_H
#define VIZZY_MSGS_MESSAGE_CARTESIANGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <std_msgs/Float32.h>
#include <std_msgs/Float32.h>

namespace vizzy_msgs
{
template <class ContainerAllocator>
struct CartesianGoal_
{
  typedef CartesianGoal_<ContainerAllocator> Type;

  CartesianGoal_()
    : type(0)
    , end_effector_pose()
    , velocity()
    , duration()  {
    }
  CartesianGoal_(const ContainerAllocator& _alloc)
    : type(0)
    , end_effector_pose(_alloc)
    , velocity(_alloc)
    , duration(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _end_effector_pose_type;
  _end_effector_pose_type end_effector_pose;

   typedef std::vector< ::std_msgs::Float32_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::std_msgs::Float32_<ContainerAllocator> >::other >  _velocity_type;
  _velocity_type velocity;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _duration_type;
  _duration_type duration;



  enum {
    CARTESIAN = 0u,
    HOME = 1u,
    VELOCITY = 2u,
    GRAB = 3u,
    RELEASE = 4u,
    PREEMPT = 5u,
  };


  typedef boost::shared_ptr< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianGoal_

typedef ::vizzy_msgs::CartesianGoal_<std::allocator<void> > CartesianGoal;

typedef boost::shared_ptr< ::vizzy_msgs::CartesianGoal > CartesianGoalPtr;
typedef boost::shared_ptr< ::vizzy_msgs::CartesianGoal const> CartesianGoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vizzy_msgs::CartesianGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vizzy_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'vizzy_msgs': ['/home/miguel/catkin_ws/devel/share/vizzy_msgs/msg', '/home/miguel/catkin_ws/src/vizzy/vizzy_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f363fa97393b5c8280ca1eb3765f4c8e";
  }

  static const char* value(const ::vizzy_msgs::CartesianGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf363fa97393b5c82ULL;
  static const uint64_t static_value2 = 0x80ca1eb3765f4c8eULL;
};

template<class ContainerAllocator>
struct DataType< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vizzy_msgs/CartesianGoal";
  }

  static const char* value(const ::vizzy_msgs::CartesianGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
uint8 CARTESIAN=0\n\
uint8 HOME=1\n\
uint8 VELOCITY=2\n\
uint8 GRAB=3\n\
uint8 RELEASE=4\n\
uint8 PREEMPT=5\n\
uint8 type\n\
\n\
geometry_msgs/PoseStamped end_effector_pose\n\
std_msgs/Float32[] velocity\n\
std_msgs/Float32 duration\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::vizzy_msgs::CartesianGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.end_effector_pose);
      stream.next(m.velocity);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vizzy_msgs::CartesianGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vizzy_msgs::CartesianGoal_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "end_effector_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.end_effector_pose);
    s << indent << "velocity[]" << std::endl;
    for (size_t i = 0; i < v.velocity.size(); ++i)
    {
      s << indent << "  velocity[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "    ", v.velocity[i]);
    }
    s << indent << "duration: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIZZY_MSGS_MESSAGE_CARTESIANGOAL_H
