// Generated by gencpp from file rail_segmentation/RemoveObjectRequest.msg
// DO NOT EDIT!


#ifndef RAIL_SEGMENTATION_MESSAGE_REMOVEOBJECTREQUEST_H
#define RAIL_SEGMENTATION_MESSAGE_REMOVEOBJECTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rail_segmentation
{
template <class ContainerAllocator>
struct RemoveObjectRequest_
{
  typedef RemoveObjectRequest_<ContainerAllocator> Type;

  RemoveObjectRequest_()
    : index(0)  {
    }
  RemoveObjectRequest_(const ContainerAllocator& _alloc)
    : index(0)  {
  (void)_alloc;
    }



   typedef uint32_t _index_type;
  _index_type index;





  typedef boost::shared_ptr< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RemoveObjectRequest_

typedef ::rail_segmentation::RemoveObjectRequest_<std::allocator<void> > RemoveObjectRequest;

typedef boost::shared_ptr< ::rail_segmentation::RemoveObjectRequest > RemoveObjectRequestPtr;
typedef boost::shared_ptr< ::rail_segmentation::RemoveObjectRequest const> RemoveObjectRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rail_segmentation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad7b979103dbd563a352ef5270716728";
  }

  static const char* value(const ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad7b979103dbd563ULL;
  static const uint64_t static_value2 = 0xa352ef5270716728ULL;
};

template<class ContainerAllocator>
struct DataType< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rail_segmentation/RemoveObjectRequest";
  }

  static const char* value(const ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 index\n\
";
  }

  static const char* value(const ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RemoveObjectRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rail_segmentation::RemoveObjectRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.index);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAIL_SEGMENTATION_MESSAGE_REMOVEOBJECTREQUEST_H
