// Generated by gencpp from file vizzy_msgs/GazeGoal.msg
// DO NOT EDIT!


#ifndef VIZZY_MSGS_MESSAGE_GAZEGOAL_H
#define VIZZY_MSGS_MESSAGE_GAZEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PointStamped.h>

namespace vizzy_msgs
{
template <class ContainerAllocator>
struct GazeGoal_
{
  typedef GazeGoal_<ContainerAllocator> Type;

  GazeGoal_()
    : type(0)
    , mode(0)
    , fixation_point()
    , fixation_point_error_tolerance(0.0)  {
    }
  GazeGoal_(const ContainerAllocator& _alloc)
    : type(0)
    , mode(0)
    , fixation_point(_alloc)
    , fixation_point_error_tolerance(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _type_type;
  _type_type type;

   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _fixation_point_type;
  _fixation_point_type fixation_point;

   typedef double _fixation_point_error_tolerance_type;
  _fixation_point_error_tolerance_type fixation_point_error_tolerance;



  enum {
    FIXATION_POINT = 0u,
    HOME = 1u,
    JOINT_VELOCITIES = 2u,
    CARTESIAN = 0u,
    JOINT = 1u,
  };


  typedef boost::shared_ptr< ::vizzy_msgs::GazeGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vizzy_msgs::GazeGoal_<ContainerAllocator> const> ConstPtr;

}; // struct GazeGoal_

typedef ::vizzy_msgs::GazeGoal_<std::allocator<void> > GazeGoal;

typedef boost::shared_ptr< ::vizzy_msgs::GazeGoal > GazeGoalPtr;
typedef boost::shared_ptr< ::vizzy_msgs::GazeGoal const> GazeGoalConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vizzy_msgs::GazeGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vizzy_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'vizzy_msgs': ['/home/miguel/catkin_ws/devel/share/vizzy_msgs/msg', '/home/miguel/catkin_ws/src/vizzy/vizzy_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vizzy_msgs::GazeGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vizzy_msgs::GazeGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vizzy_msgs::GazeGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a1b8bf39eac0adbf0be2f97a6f149676";
  }

  static const char* value(const ::vizzy_msgs::GazeGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa1b8bf39eac0adbfULL;
  static const uint64_t static_value2 = 0x0be2f97a6f149676ULL;
};

template<class ContainerAllocator>
struct DataType< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vizzy_msgs/GazeGoal";
  }

  static const char* value(const ::vizzy_msgs::GazeGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
uint8 FIXATION_POINT=0\n\
uint8 HOME=1             # POSITION ERROR SUPPRESSION\n\
uint8 JOINT_VELOCITIES=2 # VELOCITY SUPPRESSION\n\
uint8 type\n\
\n\
uint8 CARTESIAN=0\n\
uint8 JOINT=1\n\
uint8 mode  # ONLY CARTESIAN IS IMPLEMENTED\n\
\n\
\n\
geometry_msgs/PointStamped fixation_point\n\
\n\
float64 fixation_point_error_tolerance  # max allowed error in meters\n\
#float64 suppression_velocity # max allowed velocity in radians\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::vizzy_msgs::GazeGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.mode);
      stream.next(m.fixation_point);
      stream.next(m.fixation_point_error_tolerance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GazeGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vizzy_msgs::GazeGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vizzy_msgs::GazeGoal_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "fixation_point: ";
    s << std::endl;
    Printer< ::geometry_msgs::PointStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.fixation_point);
    s << indent << "fixation_point_error_tolerance: ";
    Printer<double>::stream(s, indent + "  ", v.fixation_point_error_tolerance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VIZZY_MSGS_MESSAGE_GAZEGOAL_H
